# Generated by Django 4.1.3 on 2023-06-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('capital', models.CharField(max_length=200)),
                ('dialingCode', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('population', models.IntegerField()),
                ('officialLanguage', models.CharField(max_length=200)),
                ('mapImage', models.ImageField(blank=True, null=True, upload_to='images')),
                ('countryFlag', models.ImageField(blank=True, null=True, upload_to='images')),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseapp.country')),
            ],
        ),
    ]
