# Generated by Django 4.1.3 on 2023-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0005_continent_continentgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='climate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
