# Generated by Django 4.1.3 on 2023-07-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0006_country_climate_country_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
