# Generated by Django 4.1.3 on 2023-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0007_alter_country_population'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='wikiLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
