# Generated by Django 4.1.3 on 2023-07-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0008_country_culture_country_wikilink'),
    ]

    operations = [
        migrations.AddField(
            model_name='continent',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='beliefs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='climate',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='countries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='culture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='currency',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='density',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='flavours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='gdp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='goods',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='mapImage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='continent',
            name='population',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='continent',
            name='wikiLink',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
