# Generated by Django 4.1.3 on 2023-07-01 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0010_rename_continent_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='currency',
        ),
    ]
