# Generated by Django 4.1.3 on 2023-07-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0011_remove_region_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='timezone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
