# Generated by Django 4.1.3 on 2023-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0012_region_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='coverPhoto1',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='country',
            name='coverPhoto2',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='country',
            name='coverPhoto3',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
